import Foundation

/// Profile of a project's tech stack and structure.
///
/// Contains detected languages, frameworks, and basic metadata about the project
/// directory. Generated by ``ProjectStackAnalyzer``.
///
/// - Since: 0.9.0
public struct ProjectProfile: Codable, Sendable, Equatable {
    /// The analyzed directory path.
    public let directory: String

    /// Detected programming languages (sorted alphabetically).
    public let languages: [String]

    /// Detected frameworks and build tools (sorted alphabetically).
    public let frameworks: [String]

    /// Whether the directory contains a README.md file.
    public let hasReadme: Bool

    /// Whether the directory contains a CLAUDE.md file.
    public let hasClaudeMd: Bool

    /// Whether the directory is a git repository.
    public let hasGit: Bool

    /// Estimated number of source code files.
    public let estimatedFileCount: Int

    /// Estimated number of lines of source code.
    public let estimatedLineCount: Int

    /// Creates a project profile.
    public init(
        directory: String,
        languages: [String],
        frameworks: [String],
        hasReadme: Bool,
        hasClaudeMd: Bool,
        hasGit: Bool,
        estimatedFileCount: Int,
        estimatedLineCount: Int
    ) {
        self.directory = directory
        self.languages = languages
        self.frameworks = frameworks
        self.hasReadme = hasReadme
        self.hasClaudeMd = hasClaudeMd
        self.hasGit = hasGit
        self.estimatedFileCount = estimatedFileCount
        self.estimatedLineCount = estimatedLineCount
    }
}
